"""Add trial_end_date to User model

Revision ID: bb3a83cd9f49
Revises: 816c30d84bfc
Create Date: 2024-11-30 22:32:00.882790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3a83cd9f49'
down_revision = '816c30d84bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('trial_end_date')

    # ### end Alembic commands ###
